# Nice centralized area to redefine our JES uncertainties
# of interest as we study them


def getUncerts() :
    uncertNames = [
            "AbsoluteFlavMap",
            "AbsoluteMPFBias",
            "AbsoluteScale",
            "AbsoluteStat",
    #        #"CorrelationGroupFlavor",
    #        #"CorrelationGroupIntercalibration",
    #        #"CorrelationGroupMPFInSitu",
    #        #"CorrelationGroupUncorrelated",
    #        #"CorrelationGroupbJES",
    #        #"FlavorPhotonJet",
    #        #"FlavorPureBottom",
    #        #"FlavorPureCharm",
    #        #"FlavorPureGluon",
    #        #"FlavorPureQuark",
    #        "FlavorQCD",
    #        #"FlavorZJet",
    #        "Fragmentation",
    #        "PileUpDataMC",
    #        #"PileUpEnvelope",
    #        "PileUpMuZero",
    #        "PileUpPtBB",
    #        "PileUpPtEC1",
    #        "PileUpPtEC2",
    #        "PileUpPtHF",
    #        "PileUpPtRef",
    #        "RelativeFSR",
    #        "RelativeJEREC1",
    #        "RelativeJEREC2",
    #        "RelativeJERHF",
    #        "RelativePtBB",
    #        "RelativePtEC1",
    #        "RelativePtEC2",
    #        "RelativePtHF",
    #        "RelativeStatEC",
    #        "RelativeStatFSR",
    #        "RelativeStatHF",
    #        "SinglePionECAL",
    #        "SinglePionHCAL",
    #        #"SubTotalAbsolute",
    #        #"SubTotalMC",
    #        #"SubTotalPileUp",
    #        #"SubTotalPt",
    #        #"SubTotalRelative",
    #        #"SubTotalScale",
    #        "TimePtEta",
            #"TimeRunBCD",
            #"TimeRunE",
            #"TimeRunF",
            #"TimeRunGH",
            #"TotalNoFlavorNoTime",
            #"TotalNoFlavor",
            #"TotalNoTime",
            "Total",
            "Closure",]
    return uncertNames



